name = "cartfullofx"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[env.production]
# Production deployment for cartfullofx.com (main Cozyartz site)
compatibility_date = "2024-01-01"

[env.preview]
# Staging deployment will use pages.dev subdomain
compatibility_date = "2024-01-01"