name = "wantthissite"
compatibility_date = "2024-07-01"
pages_build_output_dir = "dist"

# Cloudflare Workers AI Configuration
# Set these as environment variables or use wrangler secret commands:
# wrangler secret put CLOUDFLARE_ACCOUNT_ID
# wrangler secret put CLOUDFLARE_API_TOKEN
# Optional: wrangler secret put OPENAI_API_KEY

[env.production]
# Production deployment for wantthissite.com
compatibility_date = "2024-07-01"

[env.preview]  
# Preview deployments for PR testing
compatibility_date = "2024-07-01"