name = "cartx"
compatibility_date = "2024-07-01"
pages_build_output_dir = "dist"

[env.production]
# Production deployment for cartfullofx.com
compatibility_date = "2024-07-01"

[env.preview]  
# Preview deployments for PR testing
compatibility_date = "2024-07-01"